services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: brasileirao_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - brasileirao_net

  db:
    image: postgres:15
    container_name: brasileirao_postgres
    restart: always
    ports:
      - "25432:5432" 
    volumes:
      - ./backend/app/db/sql/dump.sql:/docker-entrypoint-initdb.d/dump.sql:ro
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - brasileirao_net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: brasileirao_frontend
    ports:
      - "3000:3000"
    # volumes:
    #   - frontend_node_modules:/app/node_modules
    #   - ./frontend:/app
    stdin_open: true
    tty: true
    networks:
      - brasileirao_net

volumes:
  postgres-data:
  frontend_node_modules:

networks:
  brasileirao_net:
    driver: bridge