services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: brasileirao_backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: brasileirao_postgres
    restart: always
    ports:
      - "25432:5432" 
    volumes:
      - ./backend/app/db/sql/dump.sql:/docker-entrypoint-initdb.d/dump.sql:ro
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: brasileirao_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    stdin_open: true
    tty: true

volumes:
  postgres-data:
