name: Backend CI

on:
  push:
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yaml"
  pull_request:
    paths:
      - "backend/**"
      - ".github/workflows/backend-ci.yaml"

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies (backend)
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 ruff black

      - name: Run Ruff (backend)
        working-directory: backend
        run: ruff check .

      - name: Run Black (check mode, backend)
        working-directory: backend
        run: black --check .

      - name: Run Flake8 (backend)
        working-directory: backend
        run: flake8 .

      - name: Build and start containers
        run: docker compose up -d --build backend

      - name: Run tests inside backend container
        run: docker exec -it brasileirao_backend pytest
